ABS.Web/Controllers/AirlineController.cs
using ABS.Data;
using ABS.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ABSMVC.Controllers
{
    public class AirlineController : Controller
    {
        private readonly AirlineRepository db;
        public AirlineController()
        {
            db = new AirlineRepository();
        }

        // GET: Airline
        public ActionResult Index()
        {
            var model = db.Retreive();
            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Airline airline)
        {
            if(ModelState.IsValid)
            {
                db.AddNewAirline(airline);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

ABS.Web/Controllers/AirportController.cs
using ABS.Data;
using ABS.Entities;
using ABS.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ABSMVC.Controllers
{
    public class AirportController : Controller
    {
        private readonly AirportRepository db;
        public AirportController()
        {
            db = new AirportRepository();
        }
        // GET: Airport
        public ActionResult Index()
        {
            var model = db.Retreive();
            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Airport airport)
        {
            if(ModelState.IsValid)
            {
                db.AddNewAirport(airport);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

ABS.Web/Controllers/FlightController.cs
using ABS.Data;
using ABS.Entities;
using ABS.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ABSMVC.Controllers
{
    public class FlightController : Controller
    {
        private readonly FlightRepository db;
        private readonly AirlineRepository airlines;
        private readonly AirportRepository airports;
        public FlightController()
        {
            db = new FlightRepository();
            airlines = new AirlineRepository();
            airports = new AirportRepository();
        }
        // GET: Flight
        public ActionResult Index(string sortOrder, string originAirport, string destinationAirport)
        {
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var model = db.Retreive();
            if (!String.IsNullOrEmpty(originAirport))
            {
                model = model.Where(f => f.OriginAirport == originAirport);
            }
            if(!String.IsNullOrEmpty(destinationAirport))
            {
                model = model.Where(f => f.DestinationAirport == destinationAirport);
            }
            switch (sortOrder)
            {
                case "Date":
                    model = model.OrderBy(s => s.Date);
                    break;
                default:
                    model = model.OrderByDescending(s => s.Date);
                    break;
            }

            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            var model = new FlightCreateViewModel();
            model.Airlines = GetAirlinesDropDown();
            model.OriginAirports = GetAirportsDropDown();
            model.DestinationAirports = GetAirportsDropDown();


            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Flight flight)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    db.AddNewFlight(flight);
                }
                catch(Exception e)
                {
                    return RedirectToAction("Error", new { message = e.Message });
                }
               return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Error(string message)
        {
            ViewBag.Message = message;
            return View();
        }


        public List<SelectListItem> GetAirlinesDropDown()
        {
            List<SelectListItem> ls = new List<SelectListItem>();
            var lm = airlines.Retreive();
            foreach (var airline in lm)
            {
                ls.Add(new SelectListItem() { Text = airline.Name, Value = airline.AirlineId.ToString() });
            }
            return ls;
        }

        public List<SelectListItem> GetAirportsDropDown()
        {
            List<SelectListItem> ls = new List<SelectListItem>();
            var lm = airports.Retreive();
            foreach (var airport in lm)
            {
                ls.Add(new SelectListItem() { Text = airport.Name, Value = airport.AirportId.ToString() });
            }
            return ls;
        }

    }
}

ABS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ABS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Airports", "Index", "Airport")</li>
                    <li>@Html.ActionLink("Airlines", "Index", "Airline")</li>
                    <li>@Html.ActionLink("Flights", "Index", "Flight")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>